{
	"version": 1722517264,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/solidblock-sheet0.png",
		"images/jumpthough-sheet0.png",
		"images/tilemap.png",
		"images/projectile-sheet0.png",
		"images/projectile-sheet1.png",
		"images/target-sheet0.png",
		"images/gun-sheet0.png",
		"images/knight-sheet0.png",
		"images/knight-sheet1.png",
		"images/knight-sheet2.png",
		"images/hptext.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/hppack-sheet0.png",
		"images/spawner-sheet0.png",
		"images/dmgboost-sheet0.png",
		"images/start-sheet0.png",
		"media/cancel 1.m4a",
		"media/cancel 1.ogg",
		"media/confirm 1.m4a",
		"media/confirm 1.ogg",
		"media/hit damage 1.m4a",
		"media/hit damage 1.ogg",
		"media/jump 1.m4a",
		"media/jump 1.ogg",
		"media/attack variation.m4a",
		"media/attack variation.ogg",
		"media/action 1 (loop).ogg",
		"media/light ambient 2 (loop).m4a",
		"media/light ambient 2 (loop).ogg",
		"media/night ambient 3 (loop).m4a",
		"media/night ambient 3 (loop).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}